version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3303:3306
    environment:
      MYSQL_DATABASE: licenta
      MYSQL_ROOT_PASSWORD: andrei5011221
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./StuddyBuddy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/licenta
      - spring.datasource.username=root
      - spring.datasource.password=andrei5011221
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql=true
      - my.secret.key=58bc3281da67834c1cb0286e38c895d7fe6a90a7ac15f3514da6c9c2bdcbc31c
    networks:
      springboot-mysql-net:
    restart: on-failure

  frontend:
    build: ./angular-ui-studdy-buddy
    ports:
      - 4200:4200
    depends_on:
      springboot-restful-webservices:
        condition: service_started
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
